kind: pipeline
name: 4.10.0+multicore-opam

platform:
  os: linux
  arch: amd64

steps:
- name: 4.10.0+multicore-opam
  image: ocurrent/opam:ubuntu-18.04-ocaml-4.10
  commands:
  - opam update
  - opam switch create 4.10.0+multicore --packages=ocaml-variants.4.10.0+multicore --repositories=multicore=git+https://github.com/ocaml-multicore/multicore-opam.git,default
  - eval $(opam env)
  - opam --version
  - opam switch
  - opam list
  - opam install dune domainslib
